### ISSUE TITLE
[watcher / uploading files] Give proper feedback when Shopify blocks a file from being uploaded

### ISSUE THREAD

**Issue by nickjj** [csaunders/phoenix#10]
#### Discovery

I was editing a template where I forgot to close a pagination tag and the watcher said it updated the file but the result was the file not being updated because I'm guessing Shopify blocked it at some point after the watcher tried to do its job.

#### Feature request

It would be really handy if you could listen for a response from Shopify after uploading and just parrot back the fail message in the terminal if something isn't a 200?

**Comment by csaunders** [comment]
The latest nightly has this patch so you can start using it if you'd like.
