### ISSUE TITLE
Unresolved dependencies when installing phoenix for development

### ISSUE THREAD

**Issue by nickjj** [csaunders/phoenix#14]
##### Install it
`go get github.com/csaunders/phoenix`

##### Issue
Missing dependency on `fsnotify.v1` which stops the world.

##### Temporary fix for now
`go get https://gopkg.in/fsnotify.v1`

**Comment by csaunders** [comment]
Yeah, just got around to trying this out on a new go installation and the mentioned command works.

I'll update the documentation for contributors
