### ISSUE TITLE
Point to theme folder within config.yml

### ISSUE THREAD

**Issue by reggi** [csaunders/phoenix#16]
https://github.com/Shopify/shopify_theme/issues/126

Right now using the CLI or the config you can't set the theme folder it assumes it's the current directory. I like to leave the theme files together in their own folder. Lets say I have a dir structure like this.

```
/my-theme
  -- config.yml
  -- /theme
    -- /snippets  
    -- /layouts
    -- /templates
```

How can I point to the theme folder?

**Comment by csaunders** [comment]
The changes in [0.1.0](https://github.com/csaunders/phoenix/releases/tag/0.1.0) pretty much address this. Maybe changing to `--config` or `--config-location` or something, but otherwise I think this issue is fixed.

**Comment by ckhatton** [comment]
@csaunders +9 :+1:
