### ISSUE TITLE
Upload entire theme

### ISSUE THREAD

**Issue by reggi** [csaunders/phoenix#20]
`theme-manipulate upload` should sync the version I have with the version on shopify, no?

**Comment by csaunders** [comment]
As of 0.0.4 you can now do fileglobs, so if you wanted you could say `theme-manipulate upload *` and it will push all your local changes to Shopify.

Currently there isn't a way of knowing whether a local and remote file have changed yet. That a feature on it's own, that I'd like to get to eventually.
