### ISSUE TITLE
Windows: use of double backslash in payload's path results in 404

### ISSUE THREAD

**Issue by wolverex** [csaunders/phoenix#22]
Hi,
On my Windows computer, when the application tries to perform any operation it is always met with a 404 error because the payload looks like this` {"asset":{"key":"assets\ \image.jpg"}}` (added space Github trying to escape it) which is not acceptable. it has to be a single foward slash {"asset":{"key":"assets/image.jpg"}} . Is this an issue with just my computer or Windows in general?

**Comment by csaunders** [comment]
It's probably a windows issue. I'm goofing around with keys and made the assumption that I'd be working with unix-like paths, which is probably why this is broken.

Thanks for being the first windows user to try it out.
