### ISSUE TITLE
Theme watch not uploading entire file

### ISSUE THREAD

**Issue by thisislawatts** [csaunders/phoenix#31]
This is an interesting one, perhaps tied to the size of the file being uploaded. When using `theme watch` to handle uploading [a stylesheet](https://github.com/Shopify/Timber/blob/master/assets/timber.scss.liquid) it seems to upload different amounts, my tests show it tends to drop out between lines 567–1700 (approx 45kb)

```css
.pagination-custom-lg > li:first-child > a,
.pagination-custom-lg > li:first-child > span {
  border-bottom-left-radius: 6px;
  border-top-left-ra
```

No such errors when using `theme upload`

**Comment by csaunders** [comment]
Are you using a Unix-like operating system?

Install `mitmproxy` boot it up and add the following to your `config.yml` for the appropriate environment:

```yaml
development:
  proxy: "https://localhost:8080"
```

**Comment by csaunders** [comment]
Keep an eye on that and see if anything weird is happening. Feel free to post the response here, but be vigilant to sanitize out any sensitive information (access tokens, etc.)

**Comment by thisislawatts** [comment]
Writing out the contents of `mitmdump` and it looks like it's not transmitting the complete file, so perhaps it's getting truncated down the line somewhere within the tool? I've got the source so could add some further logging and compile it out, any recommendations on where to start?

Running OSX 10.10.1

**Comment by csaunders** [comment]
that's pretty weird. A 45kb file shouldn't be causing this kind of problem.

I'll test it out with some scss files and some larger ones like an MP3 or something.

**Comment by csaunders** [comment]
How much have you modified the scss in Timber? If I were to grab the latest release I should be able to replicate the issue pretty easily eh?

**Comment by thisislawatts** [comment]
I had added a hundred lines or so, but then testing again with the unmodified version I was able to recreate it with the original. 

Quickly testing it out with https://gist.github.com/thisislawatts/bfbf7c912a9d0abc1301 <https://gist.github.com/thisislawatts/bfbf7c912a9d0abc1301> and it bails out between 2000~3400

**Comment by thisislawatts** [comment]
Were you able to recreate this issue on your side?

**Comment by csaunders** [comment]
I haven't gotten around to it yet.
