### ISSUE TITLE
Installation and documentation links broken on gh-pages

### ISSUE THREAD

**Issue by sdn90** [csaunders/phoenix#42]
Link are set to http://csaunders.github.io/install and http://csaunders.github.io/documentation

Should be http://csaunders.github.io/phoenix/install and http://csaunders.github.io/phoenix/install

**Comment by hughker** [comment]
@csaunders — PR #43 should fix this and also make it all pretty by loading the CSS.

**Comment by csaunders** [comment]
You caught me. This requires a patch to the readme not to the links.

http://themekit.cat

**Comment by hughker** [comment]
Oh you're not using GitHub Pages @csaunders ?

**Comment by csaunders** [comment]
https://github.com/csaunders/phoenix/commit/0685d32bb49aa18b9102c3f93f8cf8e0c43be34f

**Comment by csaunders** [comment]
Yes I am, but I'm using custom domains.

https://github.com/csaunders/phoenix/commit/0685d32bb49aa18b9102c3f93f8cf8e0c43be34f

**Comment by hughker** [comment]
Of course, I should've looked for the CNAME file before asking… thanks @csaunders
