### ISSUE TITLE
[theme-watch] Using sed with -i caused a LOT of temp files to be uploaded

### ISSUE THREAD

**Issue by nickjj** [csaunders/phoenix#8]
#### What caused it?

I ran this command to do a quick and dirty recursive find/replace:

`find ./ -type f -exec sed -i -e 's/foo/bar/g' {} \;`

#### Results?

About 400 dead files uploaded to the shop, such as:

```
Recieved Update event on snippets/sedWqDfOb
[x 400ish]
```

There's no way to remove them with the watcher because they don't exist locally. Thoughts on how to remove these files without manually having to delete 400 of them by hand?

**Comment by csaunders** [comment]
Pretty sure the changes in 0.0.4 resolve this. If it's not the case, please feel free to reopen the issue.
